// Переводы сайта
const translations = {
  en: {
    'nav-catalog': 'Catalog',
    'nav-about': 'About',
    'nav-preorder': 'Preorder',
    'hero-title': 'One base. Infinite styles.',
    'hero-subtitle': 'Modular zipper system that transforms any outfit. One base on a zipper, removable pendant with custom design.',
    'cta-button': 'Leave a request',
    'catalog-title': 'PULLERS',
    'catalog-caption': 'SLIDE ONE COLLECTION',
    'product-1': 'Exclusion Zipper Base',
    'product-2': 'Exclusion EX Zipper #1',
    'product-3': 'Exclusion EX Zipper #2',
    'product-4': 'Exclusion EX Zipper #3',
    'preorder-btn': 'Preorder',
    'about-title': 'A system, not an accessory',
    'about-text-1': 'Exclusion is not just another accessory. It\'s a modular system that redefines how you customize your street wear.',
    'about-text-2': 'One base attaches to any zipper permanently. Multiple pendants mean infinite styling options for every outfit.',
    'fact-1': 'Один крепёж для всего',
    'fact-1-text': 'Один основной модуль устанавливается на молнию и служит фиксатором для всех подвесок.',
    'fact-2': 'Меняется за секунду',
    'fact-2-text': 'Съёмная подвеска быстро меняет образ без инструментов и без усилий.',
    'fact-3': 'Коллаборации с брендами и артистами',
    'fact-3-text': 'Эксклюзивные дизайны от известных креативных студий мира.',
    'preorder-section-title': 'Be first',
    'preorder-section-subtitle': 'Leave your email to get notification about sales launch and exclusive access to first drop.',
    'email-placeholder': 'your@email.com',
    'subscribe-btn': 'Subscribe',
    'success-message': 'Done. See you at the drop.',
    'copyright': '© 2025 Exclusion. All rights reserved.',
    'slogan': 'Modular zipper system. One base — infinite styles.'
  },
  ru: {
    'nav-catalog': 'Каталог',
    'nav-about': 'О бренде',
    'nav-preorder': 'Предзаказ',
    'hero-title': 'Одна основа. Бесконечно стилей.',
    'hero-subtitle': 'Модульная система молний, которая трансформирует любой аутфит. Одна основа на молнии, съёмная подвеска с кастомным дизайном.',
    'cta-button': 'Оставить заявку',
    'catalog-title': 'PULLERS',
    'catalog-caption': 'SLIDE ONE COLLECTION',
    'product-1': 'Exclusion Zipper Base',
    'product-2': 'Exclusion EX Zipper #1',
    'product-3': 'Exclusion EX Zipper #2',
    'product-4': 'Exclusion EX Zipper #3',
    'preorder-btn': 'Предзаказ',
    'about-title': 'Система, а не аксессуар',
    'about-text-1': 'Exclusion — это не просто ещё один аксессуар. Это модульная система, которая меняет подход к кастомизации уличной одежды.',
    'about-text-2': 'Одна основа крепится на молнию навсегда. Множество подвесок означают бесконечные варианты стилизации для любого наряда.',
    'fact-1': 'Один крепёж для всего',
    'fact-1-text': 'Один основной модуль устанавливается на молнию и служит фиксатором для всех подвесок.',
    'fact-2': 'Меняется за секунду',
    'fact-2-text': 'Съёмная подвеска быстро меняет образ без инструментов и без усилий.',
    'fact-3': 'Коллаборации с брендами и артистами',
    'fact-3-text': 'Эксклюзивные дизайны от известных креативных студий мира.',
    'preorder-section-title': 'Будь первым',
    'preorder-section-subtitle': 'Оставь почту — получи уведомление о старте продаж и эксклюзивный доступ к первому дропу.',
    'email-placeholder': 'your@email.com',
    'subscribe-btn': 'Подписаться',
    'success-message': 'Готово. Увидимся на дропе.',
    'copyright': '© 2025 Exclusion. All rights reserved.',
    'slogan': 'Modular zipper system. One base — infinite styles.'
  },
  by: {
    'nav-catalog': 'Каталёг',
    'nav-about': 'Аб брэндзе',
    'nav-preorder': 'Папярэдняе замовленне',
    'hero-title': 'Адна аснова. Бясконца стыляў.',
    'hero-subtitle': 'Мадулёрная сыстэма молняў, якая трансформуе любы аутфіт. Адна аснова на молніі, сььмная падвеска з кастомным дызайнам.',
    'cta-button': 'Пакінуць заяўку',
    'catalog-title': 'PULLERS',
    'catalog-caption': 'SLIDE ONE COLLECTION',
    'product-1': 'Exclusion Zipper Base',
    'product-2': 'Exclusion EX Zipper #1',
    'product-3': 'Exclusion EX Zipper #2',
    'product-4': 'Exclusion EX Zipper #3',
    'preorder-btn': 'Папярэдняе замовленне',
    'about-title': 'Сыстэма, а не аксэсуар',
    'about-text-1': 'Exclusion — гэта не проста яшчэ адзін аксэсуар. Гэта мадулёрная сыстэма, якая меняе падыход да кастамізацыі вулічнай адэзды.',
    'about-text-2': 'Адна аснова цяпаецца на молнію навечна. Вялікі філістэр падвесак азначае бясконцыя варыянты стылязіцыі для любога наряду.',
    'fact-1': 'Адзін крэпеж для усёго',
    'fact-1-text': 'Адзін асновны модуль устаноўляецца на молнію і служыць фіксатарам для усіх падвесак.',
    'fact-2': 'Мяняецца за секунду',
    'fact-2-text': 'Сььмная падвеска хутка меняе абраз без інструмэнтаў і без зусілоў.',
    'fact-3': 'Калабарацыі з брандамі і артыстамі',
    'fact-3-text': 'Эксклюзіўныя дызайны ад вядомых крэатыўных студыяў свету.',
    'preorder-section-title': 'Будь першым',
    'preorder-section-subtitle': 'Пакінуць пошту — атрымліце паведамленне пра старт продаж і эксклюзіўны доступ да першага драпу.',
    'email-placeholder': 'your@email.com',
    'subscribe-btn': 'Падпісацца',
    'success-message': 'Гатова. Убачымся на драпе.',
    'copyright': '© 2025 Exclusion. All rights reserved.',
    'slogan': 'Modular zipper system. One base — infinite styles.'
  }
};

// Цены для разных языков
const prices = {
  en: { symbol: '$', suffix: 'USD' },
  ru: { symbol: '₽', suffix: 'RUB' },
  by: { symbol: 'Br', suffix: 'BYN' }
};